#Server Port
server : 
  port : 8888

spring :
  #Oracle Setting
  datasource : 
    driver-class-name : oracle.jdbc.driver.OracleDriver
    url : jdbc:oracle:thin:@localhost:1521/xe
    username : jpanda
    password : jpanda


  mail:
    host: smtp.gmail.com 
    port: 587
    username: jpandajb501@gmail.com
    password: ldxpeltvbuvsonge
    properties:
      mail:
        smtp:
          auth: true 
          starttls:
            enable: true

  #HttpHiddenMethod
  mvc: 
    hiddenmethod:
      filter:
        enabled: true

#myBatis
mybatis: 
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/**/*.xml

